tls:
  certificates:
    - certFile: C:\etc\traefik\certs\_wildcard.blogger.localhost.pem
      keyFile: C:\etc\traefik\certs\_wildcard.blogger.localhost-key.pem
    - certFile: C:\etc\traefik\certs\blogger.xmcloudcm.localhost.pem
      keyFile: C:\etc\traefik\certs\blogger.xmcloudcm.localhost-key.pem